name: Waka Readme
on:
  schedule:
    - cron: '0 */12 * * *' # Runs every 12 hours
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with WakaTime Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update README with WakaTime stats
        uses: anmol098/waka-readme-stats@master  # ✅ CHANGED: v3.0.0 → master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_LOC_CHART: "False"
